name: Test Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          echo "TG Action Downloader"
          echo "Runner is working!"
          uname -a
          df -h
          free -h
